# Develop Maxent Mussel Model

## Convert from `.bil` to `.mxe` format
To speed model creation (from 10's of hours to 10's of minutes), convert the predictors to the Maxent `.mxe` format.

* Open command prompt and change directory by typing `c:` and then `cd C:\Users\b6pdpdem\Documents\SteamboatMusselModel`
* Create predictor_mxe folder

```java -Xmx5g -cp maxent.jar density.Convert C:\Users\b6pdpdem\Documents\SteamboatMusselModel\predictors bil C:\Users\b6pdpdem\Documents\SteamboatMusselModel\predictors_mxe mxe```


## Run Maxent


## Convert model output from 
To convert the `.mxe` format back to a format that can be read by ESRI. 

```java -Xmx5g -cp maxent.jar density.Convert C:\Users\b6pdpdem\Documents\SteamboatMusselModel\sb_existing_20181203_2 mxe C:\Users\b6pdpdem\Documents\SteamboatMusselModel\sb_existing_20181203_2 bil```

* Use the `Define Projection` tool to set the projection of the `.bil` rasters. 

## Maxent speed Issues
Follow these simple performance guidelines to reduce Maxent run time from a week to half an hour. 

* Run the model on a physical computer, not on a virtual machine. 
* Select a computer with the fastest processor and most memory available. 
* Increase the memory available to the java virtual machine (JVM). Edit the first line of the `maxent.bat` file to something like the following: `java -Xmx5g -jar maxent.jar`, where the `-Xmx` parameter sets the maximum heap size for the JVM. Set it to something less than the total amount of physical memory on your computer. 
* Do not run the model across the LAN (inputs and outputs stored on a network file system). Copy all inputs and write all outputs to the local file system.
* Use a solid state drive for storing inputs and outputs. 
* Use the "SWD" format for specifying both samples (species occurances) and environmental layers (background points). 
* Convert all predictor grids to the Maxent `.mxe` format. 
* Write all outputs to the Maxent `.mxe` format. 
* Set the `threads` parameter to at least the number of cores on your computer (or a large percentage of logical processors) to speed processing of replicates. 






